apiVersion: v1
kind: Service
metadata:
  name: service-docservice
  labels:
    app: document-service
spec:
  type: NodePort
  ports:
    - port: 9080 
      name: document-service
      nodePort: 32427
  selector:
    app: document-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-docservice
  labels:
    app: document-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: document-service
        image: us.icr.io/amsit/document-service:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9080
      imagePullSecrets:
        - name: default-us-icr-io        