apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docservice-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://us-south.git.cloud.ibm.com/devops4us/document-service