apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-deploy-docservice
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: deployment-name
        type: string
      - name: deployment-namespace
        type: string      
  steps: 
    - name: create-deployment
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(inputs.source.path)/pipeline/deployment-docservice.yml"
        - "-n env-dev"
    - name: deploy-application
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "rollout"
        - "restart"
        - "$(inputs.params.deployment-name)"
        - "-n $(inputs.params.deployment-namespace)"