apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy-docservice
spec:
  resources:
    inputs:
      - name: source
        type: git
    params:
      - name: deployment-name
        type: string
      - name: deployment-namespace
        type: string      
  steps: 
    - name: create-deployment
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(resources.inputs.source.path)/pipeline/deployment-docservice.yml"
        - "-n env-dev"
    - name: deploy-application
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "rollout"
        - "restart"
        - "deployment/deployment-docservice"
        - "-n $(resources.params.deployment-namespace)"